version: '3.3'

volumes:
    template_data: {}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: local_backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start_dev
    restart: always
    env_file: ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    container_name: local_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/nginx:/etc/nginx/conf.d
    restart: always
    env_file: ./backend/.env
    ports:
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true
  
  postgres:
    image: postgres:15.1
    container_name: local_db
    volumes:
      - template_data:/var/lib/postgresql/data
    restart: always
    env_file: ./backend/.env
    ports:
      - 5432:5432