version: '3.3'

volumes:
    template_data: {}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: local_backend
    container_name: local_backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start_dev.sh
    restart: on-failure
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    image: local_frontend
    container_name: local_frontend
    depends_on:
      - django
    volumes:
      - ./frontend:/app
    restart: on-failure
    env_file: .env
    ports:
      - 81:80
  
  postgres:
    image: postgres:15.1
    volumes:
      - template_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432