version: '3.3'

volumes:
    template_data: {}

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: local_backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    command: /start_dev
    restart: always
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    container_name: local_frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/nginx:/etc/nginx/conf.d
    restart: always
    env_file: .env
    ports:
      - 81:80
  
  postgres:
    image: postgres:15.1
    container_name: local_db
    volumes:
      - template_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432